services:
  go2rtc:
    image: alexxit/go2rtc
    #network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    ports:
      - 1984:1984
      - 8554:8554
      - 8555:8555
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=Europe/Vienna  # timezone in logs
    volumes:
      - "~/Docker/go2rtc/config:/config"   # folder for go2rtc.yaml file (edit from WebUI)
